### ISSUE TITLE
Noises

### ISSUE THREAD

**Issue by GarryGNsk** [sintech/Formanta_P432#1]
Здравствуйте! Ремонтирую данный прибор. Беспокоит шумность. У вас случайно нет схемы крайней ревизии, которая меньше шумит. Делать мод по инструкции без схемы не решаюсь.
Буду очень признателен. Моя почта timgv@mail.ru.
В Вашем эмуляторе на окончании звуков тоже слышны цифровые шумы, я так понимаю что совсем от них не избавиться с этой схемой. Спасибо

**Comment by sintech** [comment]
Ответил в почту
